test_a (__main__.lab0a.test_a)
[Lab 1] - [Investigation 1] - [Task 1] - github repository - Test for git clone ... skipped ''
test_b0 (__main__.lab0a.test_b0)
[Lab 1] - [Investigation 1] - [Task 3] - github repo details: gitlog.txt ... skipped ''
test_b1 (__main__.lab0a.test_b1)
[Lab 1] - [Investigation 1] - [Task 3] - github repo details: repo_tree.txt ... skipped ''
test_c (__main__.lab0b.test_c)
[Lab 1] - [Investigation 2] - [Part 1] - directories - Test for directory structure creation ... skipped ''
test_0 (__main__.lab1a.test_0)
[Lab 1] - [Investigation 3] - [Part 2] - printing - Test for file creation: ./lab1a.py ... ok
test_a (__main__.lab1a.test_a)
[Lab 1] - [Investigation 3] - [Part 2] - printing - Test for errors running: ./lab1a.py ... ok
test_a1 (__main__.lab1a.test_a1)
[Lab 1] - [Investigation 3] - [Part 2] - printing - Test for correct shebang line: ./lab1a.py ... ok
test_b (__main__.lab1a.test_b)
[Lab 1] - [Investigation 3] - [Part 2] - printing - Test output for correct output "Hello world": ./lab1a.py ... /usr/lib64/python3.11/subprocess.py:822: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
  _cleanup()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_0 (__main__.lab1b.test_0)
[Lab 1] - [Investigation 4] - string objects & printing - Test for file creation: ./lab1b.py ... FAIL

======================================================================
FAIL: test_0 (__main__.lab1b.test_0)
[Lab 1] - [Investigation 4] - string objects & printing - Test for file creation: ./lab1b.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wislam1/ops445/lab1/./CheckLab1.py", line 156, in test_0
    self.assertTrue( os.path.exists('./lab1b.py'), msg=error_output)
AssertionError: False is not true : your file cannot be found(HINT: make sure you AND your file are in the correct directory)

----------------------------------------------------------------------
Ran 9 tests in 0.035s

FAILED (failures=1, skipped=4)
OPS435 Lab Report - System Information for running ./CheckLab1.py
=================================================================
    User login name: wislam1
    Linux system name: fedora
    Linux system version: Fedora release 38 (Thirty Eight)
    Python executable: /usr/bin/python3
    Python version: 3115
    OS Platform: linux
    Working Directory: /home/wislam1/ops445/lab1
    Start at: Thu Sep 14 20:03:54 2023
=================================================================
